name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        with:
            source-directory: '.'
            destination-github-username: 'staadan25'
            destination-repository-name: 'staadan25.github.io'
            user-email: staadan25@gibsonek.org
            target-branch: main
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  
        
